name: Docker Image CI

on:
  push:
    branches:
        - master
        - develop
        - backendActions-1
  pull_request:
    branches:
        - master
        - develop
        - backendActions-1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

