# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
        - master
        - develop
        - backendActions-1
  pull_request:
    branches:
        - master
        - develop
        - backendActions-1

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./pokeMate

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Update Gradle Wrapper
      uses: rahulsom/gradle-up@v0.1.0
    - name: Grant execute permission for gradlew
      run: chmod +x ./pokeMate/gradlew
    - name: Wrapper
      run: ./pokeMate/gradlew wrapper
    - name: Show Gradle Tasks
      run: ./pokeMate/gradlew tasks --all
    - name: Build with Gradle
      run: ./pokeMate/gradlew build
    - name: Build with Gradle
      run: ./pokeMate/gradlew assemble
    - name: Archive backend artifact
      uses: actions/upload-artifact@v1
      with:
        name: pokeMate-backend
        path: pokeMate/build/libs/
    - uses: actions/download-artifact@v1
      with:
        name: pokemate-backend
        path: targets/artifacts
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pokemate/pokemate-backend:$(date +%s)
