# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
        - master
        - develop
  pull_request:
    branches:
        - master
        - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./pokeMate

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive backend artifact
      uses: actions/upload-artifact@v1
      with:
        name: pokeMate-backend
        path: build/libs/
